make-price: 4000
make-grinder-price: 5000
make-lottery-pool-price: 10000
make-trees-felling-machine-price: 1000
start-trees-felling-machine-price: 4000
lottery-price: 800
music-stick-price: 10
exp-saver-upgrade-base-price: 5000
exp-saver-upgrade-level-price: 1000
exp-saver-max-structure-level: 50
exp-saver-anvil-upgrade-need: 20
exp-saver-remove-repaircost-exp: 8000
exp-saver-remove-repaircost-price: 10000
anti-thunder-price: 60
anti-thunder-cycle: 3600
adv-furnace-price: 1000
winter-mode: false
sync-realtime-worlds:
  new_world: 0

wrench-price: 
  world: 200
  world_nether: 200
  world_the_end: 200
  other: 200
flint-unit:
  FLINT: 16
  OBSIDIAN: 24
air:
  world:
    oxygen: 210
    nitrogen: 780
    Ar: 10
  world_nether:
    oxygen: 100
    nitrogen: 500
    Ar: 10
    CO: 5
    CO2: 500
    SO2: 40
  world_the_end:
    oxygen: 10
    nitrogen: 10
    hydrogen: 100
    CH4: 20
material:
  GRASS_BLOCK: 7